name: Fullwidth & Invisible Char Guard

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for fullwidth punctuation & invisible chars
        shell: bash
        run: |
          set -euo pipefail
          echo "=== Start scanning ==="

          # 需要拦截的字符：
          # 全角标点： 。 ， ： ； （ ） 【 】 及全角空格
          # 中文引号： “ ” ‘ ’
          # 常见不可见字符：零宽空格(ZWSP \u200B)、零宽不连字(ZWNJ \u200C)、零宽连字(ZWJ \u200D)、BOM(\uFEFF)
          PATTERN='[。，“”‘’：；（）【】　\u200B\u200C\u200D\uFEFF]'

          found=0

          # 逐文件扫描并打印命中行（带行号）
          while IFS= read -r file; do
            # 跳过二进制/大文件目录（按需增减）
            case "$file" in
              node_modules/*|.git/*|*.png|*.jpg|*.jpeg|*.gif|*.webp|*.ico|*.pdf|*.woff|*.woff2|*.ttf|*.otf)
                continue
                ;;
            esac

            if grep -n -P "$PATTERN" -- "$file" >/dev/null 2>&1; then
              echo "⚠️  $file"
              # 打印命中行（行号:内容）
              grep -n -P "$PATTERN" -- "$file" || true
              echo
              found=1
            fi
          done < <(git ls-files)

          if [[ "$found" -ne 0 ]]; then
            echo "::error ::Detected fullwidth or invisible characters in repository. See lines above."
            exit 1
          fi

          echo "✅ No fullwidth or invisible characters found."

      # 可选：将失败时的提示写得更醒目
      - name: Tips to fix (only runs on failure)
        if: failure()
        run: |
          echo ""
          echo "修复方法："
          echo "1) 打开上面列出的文件，在对应行把中文全角符号替换为英文半角："
          echo "   。→.  ，→,  ：→:  ；→;  “ ”→\"  ‘ ’→'  （ ）→( )  【 】→[ ]  全角空格→半角空格"
          echo "2) 对不可见字符：删除零宽空格/ZWJ/ZWNJ/BOM（通常是复制粘贴造成的）。"
          echo "3) 提交后本工作流会再次检查；绿灯后再看 Vercel 构建。"
